### ISSUE TITLE
[BUG] "reference binding to null pointer of type 'BigOFunc'" with GCC UBSan

### ISSUE THREAD

**Issue by laurynas-biveinis** [google/benchmark#1196]
**Describe the bug**
Running with GCC (but not clang) Undefined Behavior Sanitizer results in runtime error on startup:
```
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1" ctest -V
1: Test command: /Users/laurynas/unodb/benchmark/build/test/benchmark_test "--benchmark_min_time=0.01"
1: Test timeout computed to be: 10000000
1: 2021-07-01T06:33:40+03:00
1: Running /Users/laurynas/unodb/benchmark/build/test/benchmark_test
1: Run on (12 X 2900 MHz CPU s)
1: CPU Caches:
1:   L1 Data 32 KiB (x6)
1:   L1 Instruction 32 KiB (x6)
1:   L2 Unified 256 KiB (x6)
1:   L3 Unified 12288 KiB (x1)
1: Load Average: 3.74, 4.20, 3.98
1: /Users/laurynas/unodb/benchmark/src/benchmark_api_internal.h:35:49: runtime error: reference binding to null pointer of type 'BigOFunc'
1:     #0 0x10af17c38 in benchmark::internal::BenchmarkRunner::DoOneRepetition() (benchmark_test:x86_64+0x1001fdc38)
1: 
 1/68 Test  #1: benchmark ..................................Subprocess aborted***Exception:   0.55 sec
...
```

**System**
Which OS, compiler, and compiler version are you using:
  - OS: macOS 11.4
  - Compiler and version: GCC 10 and 11 (Clang 11 and 12 are OK).

**To reproduce**
1. Checkout Benchmark at v1.5.5, ```cd benchmark && git clone https://github.com/google/googletest.git googletest```
2. `mkdir build && cd build && cmake ... -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-fsanitize=undefined -DCMAKE_CXX_FLAGS=-fsanitize=undefined -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10`
3. `make`
4. `UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1" ctest -V`

**Expected behavior**
No UBSan errors

**Additional context**
The issue reproduces with v1.5.4 and v1.5.5, does not reproduce with v1.5.3.

**Comment by dominichamon** [comment]
i didn't realize we could get different sanitizer behaviour between gcc and clang. but of course we can.

as part of fixing this we should probably add gcc compiler to the existing sanitizer build bots.

**Comment by dominichamon** [comment]
reproducible in debug too: 

```
/home/dominic/git/benchmark/src/benchmark_api_internal.h:35:49: runtime error: reference binding to null pointer of type 'BigOFunc'
    #0 0x5606a45caf25 in benchmark::internal::BenchmarkInstance::complexity_lambda() const /home/dominic/git/benchmark/src/benchmark_api_internal.h:35
    #1 0x5606a45c4e19 in CreateRunReport /home/dominic/git/benchmark/src/benchmark_runner.cc:97
    #2 0x5606a45c95ec in benchmark::internal::BenchmarkRunner::DoOneRepetition() /home/dominic/git/benchmark/src/benchmark_runner.cc:326
    #3 0x5606a44e6c55 in RunBenchmarks /home/dominic/git/benchmark/src/benchmark.cc:351
    #4 0x5606a44e8430 in benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) /home/dominic/git/benchmark/src/benchmark.cc:497
    #5 0x5606a44e7813 in benchmark::RunSpecifiedBenchmarks() /home/dominic/git/benchmark/src/benchmark.cc:438
    #6 0x5606a44cfd6a in main /home/dominic/git/benchmark/test/benchmark_test.cc:245
    #7 0x7f042ca74d09 in __libc_start_main ../csu/libc-start.c:308
    #8 0x5606a44c9d19 in _start (/home/dominic/git/benchmark/_build/test/benchmark_test+0x15bd19)
```

**Comment by andrewkcorcoran** [comment]
Is there going to be a bugfix release to address this issue?

**Comment by dominichamon** [comment]
i'll prepare one.
