### ISSUE TITLE
[BUG] libpfm bazel integration usage not obvious

### ISSUE THREAD

**Issue by jwbee** [google/benchmark#1543]
The possibility of using bazel to build benchmark with pfm was added recently in PR #1520. But as far as I can tell the obvious way of doing so doesn't work, because bazel can't find the pfm build file inside the benchmark repo.

If I put this in WORKSPACE:

```
http_archive(
    name = "com_github_google_benchmark",
    strip_prefix = "benchmark-bd721f9859e50b261b7afe8a262a11c25b292aa5",
    urls = ["https://github.com/google/benchmark/archive/bd721f9859e50b261b7afe8a262a11c25b292aa5.zip"],
)
load("@com_github_google_benchmark//:bazel/benchmark_deps.bzl", "benchmark_deps")
benchmark_deps()
```

Then I get this error from bazel:
```
ERROR: An error occurred during the fetch of repository 'libpfm':
   Traceback (most recent call last):
	File "/home/jwb/.cache/bazel/_bazel_jwb/890e4d4e1f99a0af6836f3d9535d08f3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/home/jwb/.cache/bazel/_bazel_jwb/890e4d4e1f99a0af6836f3d9535d08f3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Unable to load package for //tools:libpfm.BUILD.bazel: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/jwb/tiny2q/tools
ERROR: /home/jwb/tiny2q/WORKSPACE:41:15: fetching http_archive rule //external:libpfm: Traceback (most recent call last):
	File "/home/jwb/.cache/bazel/_bazel_jwb/890e4d4e1f99a0af6836f3d9535d08f3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/home/jwb/.cache/bazel/_bazel_jwb/890e4d4e1f99a0af6836f3d9535d08f3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Unable to load package for //tools:libpfm.BUILD.bazel: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/jwb/tiny2q/tools
ERROR: /home/jwb/.cache/bazel/_bazel_jwb/890e4d4e1f99a0af6836f3d9535d08f3/external/com_github_google_benchmark/BUILD.bazel:35:11: @com_github_google_benchmark//:benchmark depends on @libpfm//:libpfm in repository @libpfm which failed to fetch. no such package '@libpfm//': Unable to load package for //tools:libpfm.BUILD.bazel: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/jwb/tiny2q/tools
ERROR: Analysis of target '//:benchmark' failed; build aborted:
```

You can see it is trying to find the referenced BUILD file in my repo, instead of getting it from inside benchmark/tools.

By the way, this is bazel 6.0.0 on Linux with a clang-15 toolchain, but I doubt that matters.

To actually use the pfm integration, I had to add all of the following to my own WORKSPACE, which is partially copied from the workspace rules in benchmark.

```

http_archive(
    name = "com_github_google_benchmark",
    strip_prefix = "benchmark-bd721f9859e50b261b7afe8a262a11c25b292aa5",
    urls = ["https://github.com/google/benchmark/archive/bd721f9859e50b261b7afe8a262a11c25b292aa5.zip"],
)


http_archive(
    name = "rules_foreign_cc",
    sha256 = "2a4d07cd64b0719b39a7c12218a3e507672b82a97b98c6a89d38565894cf7c51",
    strip_prefix = "rules_foreign_cc-0.9.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://bazelbuild.github.io/rules_foreign_cc/0.9.0/flatten.html#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()

http_archive(
    name = "libpfm",
    build_file = "@com_github_google_benchmark//tools:libpfm.BUILD.bazel",
    sha256 = "5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc",
    strip_prefix = "libpfm-4.11.0",
    type = "tar.gz",
    urls = ["https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download"],
)

load("@com_github_google_benchmark//:bazel/benchmark_deps.bzl", "benchmark_deps")

benchmark_deps()
```

You can see that I had to call for the BUILD file as the fully qualified `@com_github_google_benchmark//tools:libpfm.BUILD.bazel`. Also, though this does eventually work, it only works with exactly GCC 10. Not any other GCC and not any clang.

**Comment by dmah42** [comment]
i think we're missing an "@" on line 60 of the benchmark_deps.bzl file.  it should be `            build_file = "@//tools:libpfm.BUILD.bazel",`

can you try that change locally and see if it works?
