### ISSUE TITLE
Exception thrown by benchmark::NumCPUs

### ISSUE THREAD

**Issue by facontidavide** [google/benchmark#158]
Hi,

I tried to run the most basic example presented in the documentation but I get the following error (backtrace from gdb):

```
#0  0x00007ffff722bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff722f0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff7b36535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7b346d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7b34703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7b34922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b867e0 in std::__throw_system_error(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000000000434240 in std::call_once<void (&)()> (__once=..., 
    __f=@0x433547: {void (void)} 0x433547 <benchmark::(anonymous namespace)::InitializeSystemInfo()>)
    at /usr/include/c++/4.8/mutex:794
#8  0x0000000000433f58 in benchmark::NumCPUs () at /home/icarus/Software/benchmark/src/sysinfo.cc:383
#9  0x0000000000433f86 in benchmark::CpuScalingEnabled () at /home/icarus/Software/benchmark/src/sysinfo.cc:402
#10 0x0000000000434b3b in benchmark::walltime::(anonymous namespace)::UseCpuCycleClock ()
    at /home/icarus/Software/benchmark/src/walltime.cc:197
#11 0x0000000000434c00 in benchmark::walltime::Now () at /home/icarus/Software/benchmark/src/walltime.cc:214
#12 0x0000000000424598 in benchmark::Initialize (argc=0x7fffffffdd8c, argv=0x7fffffffde78)
    at /home/icarus/Software/benchmark/src/benchmark.cc:915
```

My system:
*  gcc 4.8.4
*  Ubuntu 14.04 64 bits
* running on a virtualmachine (VirtualBox)

**Comment by dominichamon** [comment]
what was your command line for building? did you -lpthread as per the documentation?

**Comment by facontidavide** [comment]
my fault. -lpthread fixed the problem.
