### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by IgorGanapolsky** [google/benchmark#822]
When running `AutoBoxingBenchmark` test, it fails with:
> java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x30000000 cmp=com.example.benchmark.test/androidx.benchmark.IsolationActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1558468971859 and now the last time the queue went idle was: 1558468971968. If these numbers are the same your activity might be hogging the event queue.
at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:453)
at androidx.benchmark.IsolationActivity$Companion.launchSingleton(IsolationActivity.kt:105)
at androidx.benchmark.AndroidBenchmarkRunner.waitForActivitiesToComplete(AndroidBenchmarkRunner.kt:125)
at androidx.test.runner.AndroidJUnitRunner$1.run(AndroidJUnitRunner.java:443)
at androidx.test.internal.runner.listener.ActivityFinisherRunListener.testStarted(ActivityFinisherRunListener.java:48)
at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
at org.junit.internal.runners.model.EachTestNotifier.fireTestStarted(EachTestNotifier.java:42)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:323)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
benchmark:            15 ns AutoBoxingBenchmark.integerArtCacheAlloc

Any ideas?

**Comment by IgorGanapolsky** [comment]
Actually, this happens when the device screen is turned off...

**Comment by dominichamon** [comment]
The benchmark itself isn't part of this project, and I don't recognise any
of the callstack as being either. Perhaps you're looking for
https://developer.android.com/jetpack/androidx/releases/benchmark which is
an unrelated (though unfortunately similarly named) project?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*
